phrase:
  access_token: 81cfd64c6c9b068ae73adef2c828b21e82f9099d7f75aa0dc9d024b76585be6c
  project_id: b0b1a8c6184fa2a3bba4c42871a1ff4a
  push:
    sources:
    - file: ./<locale_name>.json
      params:
        file_format: react_simple_json
  pull:
    targets:
    - file: ./<locale_name>.json
      params:
        file_format: react_simple_json
