phrase:
  access_token: c6b3c39377edbf4bc22d434fcacd3eb569f9c533eadba144e67d1b7216130d4a
  project_id: b0b1a8c6184fa2a3bba4c42871a1ff4a
  push:
    sources:
    - file: ./ClientApp/src/language/en.json
      params:
        file_format: react_nested_json
  pull:
    targets:
    - file: ./ClientApp/src/language/<locale_code>.json
      params:
        file_format: react_nested_json
